@startchen ERDiag

' Entities
entity User {
  email: string <<key>>
  hashed_password : string
  registered : boolean
}

entity Team {
  team_id : int <<key>>
  team_name : string
  city : string
  conference : string
  division : string
}

entity Player {
  player_id : int <<key>>
  player_name : string
  team_id : int <<fk>>
  position : string
  age : int
}

entity Game {
  game_id : int <<key>>
  game_date : date
  home_team_id : int <<fk>>
  away_team_id : int <<fk>>
  result : string
  home_team_score : int
  away_team_score : int
}

entity Statistics {
  stat_id : int <<key>>
  player_id : int <<fk>>
  team_id : int<<fk>>
  game_id : int <<fk>>
  points : int
  rebounds : int
  assists : int
  fg_scored : int 
  fg_percentage : float
  three_pt_scored : int 
  three_pt_percentage : float
  ft_scored : int
  ft_percentage : float
  steals : int
  blocks :  int
  turnovers : int
}

entity Prediction {
  prediction_id : int <<key>>
  game_id : int <<fk>>
  player_id : int <<fk>>
  team_id : int <<fk>>
  predicted_points : float
  predicted_rebounds : float
  predicted_assists : float
  confidence_score : float
}

entity MLModel {
  model_id: int <<key>>
  model_name: string
  accuracy : float
  last_trained : datetime
 }

entity SearchHistory {
  search_id : int <<key>>
  search_query : string
  timestamp : datetime
}

entity Registration {
  registration_id : int <<key>>
  user_id : int <<fk>>
  date_registered : datetime
}

entity MLLogs {
  log_id : int <<key>>
  model_id : int <<fk>>
  prediction_id : int<<fk>>
  actual_outcome : string
  error_rate : float
}

' Relationships
relationship Plays_For { 
}
relationship Records { 
}
relationship Predicts { 
}
relationship Evaluates { 
}
relationship Trains {
}
relationship Registers { 
}
relationship Searches { 
}
relationship Favorite_Player { 
}

relationship Favorite_Team {

}

relationship Get_Stats {

}

' Connections
User -N- Registers
Registers -1- Registration

User -N- Favorite_Team
Favorite_Team -1- Team
User -N- Favorite_Player
Favorite_Player -1- Player

User -N- Searches
Searches -1- SearchHistory

Player -N- Plays_For
Plays_For -1- Team

Game -N- Records
Records -1- Statistics

Game -N- Predicts
Predicts -1- Prediction

MLModel -N- Trains
Trains -1- MLLogs

MLLogs -N- Evaluates
Evaluates -1- Prediction

Team -N- Get_Stats
Get_Stats -N- Statistics

@endchen
