name: Notify Discord on Bug Issues
on:
    issues:
        types: [labeled]
jobs:
    notify-discord:
        runs-on: ubuntu-latest
        if: github.event.label.name == 'bug'
        steps:
            - name: Send Discord Notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              run: |
                  curl -H "Content-Type: application/json" \
                       -X POST \
                       -d "{
                         \"embeds\": [{
                           \"title\": \"🚨 New Bug Report: ${{ github.event.issue.title }}\",
                           \"description\": \"${{ github.event.issue.body }}\",
                           \"url\": \"${{ github.event.issue.html_url }}\",
                           \"color\": 16711680,
                           \"author\": {
                             \"name\": \"${{ github.event.issue.user.login }}\"
                           }
                         }]
                       }" \
                       "$DISCORD_WEBHOOK"
